#!/usr/bin/env python3
"""
Minimal MCP-style example tool.

This file provides two small, useful things for examples and tests:

- process_request(payload: dict) -> dict
    Accepts a JSON-like payload, generates a minimal package using
    the local template generator in `agent/agent.py`, and returns a
    result mapping of created files.

- A tiny HTTP endpoint (optional) that accepts POST /mcp with JSON
    body and returns JSON. The HTTP server is intentionally dependency-free
    (uses Python stdlib) for the example.

Usage (test mode):
    python agent/mcp_server.py --test '{"name":"samplepkg","description":"desc","out":"./tmp_output"}'

Usage (server):
    python agent/mcp_server.py --serve --port 8000

Note: this is an example for local development and testing.
"""

import json
import argparse
import importlib.util
from pathlib import Path
from http.server import HTTPServer, BaseHTTPRequestHandler
from typing import Dict, Any

# Import the local generator to reuse the existing template logic.
# Use a file-based import so this script works whether `agent` is a package
# or a plain directory with `agent.py`.
_agent_path = Path(__file__).resolve().parent / "agent.py"
if not _agent_path.exists():
    # fallback to sibling module name
    _agent_path = Path(__file__).resolve().parent / "agent" / "agent.py"
if not _agent_path.exists():
    raise RuntimeError(f"cannot find agent.py at {_agent_path}")

spec = importlib.util.spec_from_file_location("agent_module", str(_agent_path))
agent_mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(agent_mod)
generate_local_package = agent_mod.generate_local_package


def process_request(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Process an MCP-style request payload.

    Expected payload keys:
      - name: package name (required)
      - description: package description (optional)
      - out: output directory (optional, defaults to ./tmp_output)

    Returns a dict with status and list of created file paths.
    """
    name = payload.get("name")
    if not name:
        return {"status": "error", "error": "'name' is required"}
    desc = payload.get("description", "A package generated by MCP example")
    out = Path(payload.get("out", "./tmp_output"))
    # Generate package using local template generator
    generate_local_package(out, name, desc)

    created = [
        str(out / name / "__init__.py"),
        str(out / name / "main.py"),
        str(out / "setup.py"),
        str(out / "README.md"),
        str(out / "tests" / f"test_{name}.py"),
    ]
    return {"status": "ok", "created": created}


class MCPHandler(BaseHTTPRequestHandler):
    def _send_json(self, obj, code=200):
        body = json.dumps(obj).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        if self.path != "/mcp":
            self._send_json({"error": "not found"}, code=404)
            return
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length)
        try:
            payload = json.loads(raw.decode("utf-8"))
        except Exception as e:
            self._send_json({"status": "error", "error": f"invalid json: {e}"}, code=400)
            return
        result = process_request(payload)
        self._send_json(result)


def serve(addr: str = "0.0.0.0", port: int = 8000):
    server = HTTPServer((addr, port), MCPHandler)
    print(f"MCP example server listening on http://{addr}:{port}/mcp")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("shutting down")
        server.server_close()


def _cli_test(arg: str):
    try:
        payload = json.loads(arg)
    except Exception:
        print("Invalid JSON payload provided to --test")
        return 2
    result = process_request(payload)
    print(json.dumps(result, indent=2))
    return 0


def main():
    p = argparse.ArgumentParser(prog="mcp-example")
    p.add_argument("--serve", action="store_true", help="start HTTP example server")
    p.add_argument("--port", type=int, default=8000)
    p.add_argument("--test", help="run a single test with a JSON payload (string)")
    args = p.parse_args()
    if args.test:
        raise SystemExit(_cli_test(args.test))
    if args.serve:
        serve(port=args.port)


if __name__ == "__main__":
    main()
